# Generated by Django 4.2.3 on 2023-07-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('nombreGrupo', models.CharField(max_length=100, verbose_name='Grupo')),
                ('nombrePagina', models.CharField(max_length=100, verbose_name='Pagina')),
                ('linkGrupo', models.URLField(blank=True, max_length=100, null=True)),
                ('linkPaginas', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuenta',
            },
        ),
        migrations.CreateModel(
            name='facebookapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('apikey', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Facebookapi',
                'verbose_name_plural': 'Facebookapi',
                'db_table': 'Facebookapi',
            },
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('negocio', models.CharField(max_length=100, verbose_name='Negocio')),
                ('texto', models.CharField(max_length=500)),
                ('linkPaginas', models.URLField(blank=True, max_length=100, null=True)),
                ('frecpublicacion', models.FloatField(default=24.0)),
                ('lastPOST', models.IntegerField()),
                ('activa', models.BooleanField(default='false')),
                ('cuentaFac', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='meta.cuenta')),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicacion',
                'db_table': 'publicacion',
            },
        ),
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='image/')),
                ('publicacion', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='meta.publicacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Grupo')),
                ('publicacion', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='meta.publicacion', unique=True)),
            ],
        ),
    ]
