# Generated by Django 4.2.3 on 2023-07-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='passwor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='publicacion',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='meta.publicacion'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='publicacion',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='meta.publicacion'),
        ),
    ]
