# Generated by Django 4.2.3 on 2023-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_remove_cuenta_nombre_cuenta_passwor_cuenta_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookapi',
            name='apikey',
        ),
        migrations.RemoveField(
            model_name='facebookapi',
            name='url',
        ),
        migrations.AddField(
            model_name='facebookapi',
            name='dominio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='facebookapi',
            name='identificador',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookapi',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
