# Generated by Django 4.2.3 on 2023-08-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_facebookapi_secreto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='cuentaFac',
        ),
    ]
