# Generated by Django 4.2.3 on 2023-08-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('meta', '0006_facebookapi_token_acceso_alter_imagen_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookapi',
            name='dominio',
        ),
        migrations.RemoveField(
            model_name='facebookapi',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='facebookapi',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='facebookapi',
            name='secreto',
        ),
        migrations.AddField(
            model_name='facebookapi',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='socialaccount.socialapp'),
        ),
    ]
