# Generated by Django 4.2.3 on 2023-08-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0007_remove_facebookapi_dominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookapi',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
    ]
